[package]
name = "custom-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
custom-derive-internal = { path = "../custom-derive-internal" }
syn = { version = "1", features = ["full", "fold"] }
proc-macro-crate = "0.1.5"
proc-macro2 = "1"
